# Uncomment this line to define a global platform for your project
# platform :ios, "6.0"

platform :ios, "7.0"

target "ReactiveCocoa" do
	pod 'ReactiveCocoa'
end

target "ReactiveCocoaTests" do
	pod 'ReactiveCocoa'
end

